language: cpp
os: linux
dist: trusty


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:beineri/opt-qt562-trusty'
    packages:
      - qt56base
      - qt56script
      - qt56declarative
      - qt56tools
      - qt56x11extras
      - qt56svg
      - ninja-build
      - libxcb-keysyms1-dev
      - libxml2-utils
      - libudev-dev
      - texinfo
#      - modemmanager
#      - modemmanager-dev
#      - libwayland-dev
#      - libegl1-mesa-dev
      - pkg-config
      - g++-6
      - libqrencode-dev
      - libdmtx-dev
      - libattr1-dev
      - libphonon4qt5-dev
      - libphonon4qt5experimental-dev
      - liburi-perl
      - docbook-xml
      - docbook-xsl

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

    
script:
  - source /opt/qt56/bin/qt56-env.sh
#  - ./build_frameworks.sh -i ~/kf5-debug -t Debug -g Ninja -o ~/kf5-gcc-linux64-debug.tar.xz
  - ./build_frameworks.sh -i ~/kf5-release -t Release -g Ninja -o ~/kf5-gcc-linux64-release.tar.xz -a "-DCMAKE_CXX_COMPILER=g++-6"

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash ./upload.sh ~/kf5-gcc-linux64-debug.tar.xz ~/kf5-gcc-linux64-release.tar.xz
